### ISSUE TITLE
Handover

### ISSUE THREAD

**Issue by annie-lin-hub** [pragnyakiri/UERANSIM-Handover#3]
Hi 

I try to implement "handover"  using your code, but it still have some error.
So I want to confirm how far your "handover" has developed or how to run your code correctly?

Thanks a lots

**Comment by AravindkannanCT** [comment]
@annie-lin-hub  Hi, were you able to successfully simulate handover with the hardcorded values ?

**Comment by pragnyakiri** [comment]
Handover has not been simulated completely here.

**Comment by AravindkannanCT** [comment]
Are you still working on this topic ? or do you know any resource that might be useful in this handover UE and 5g core ? thanks a lot for your time.

**Comment by pragnyakiri** [comment]
I am not working on this anymore.
